### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Derekt2**
Crowdstrike supposedly supports AMSI - see https://www.reddit.com/r/crowdstrike/comments/gw9hqt/antimalware_scan_interface_amsi/ and https://www.freepatentsonline.com/y2019/0188384.html

### CODE REVIEW

**Comment by jeffmcjunkin** [comment]
Here's some slightly more direct evidence, provided to me inside Slack from a Falcon-using friend: 
image

**Comment by subat0mik** [comment]
I'm comfortable with this data to support the CrowdStrike claim. Thanks!

**Comment by Bridgebranch** [comment]
Cybereason supports AMSI.

https://www.cybereason.com/blog/cybereason-v21.1-lts-advancing-prevention-detection-and-response

**Comment by subat0mik** [comment]
> 

Thanks! Updated the repo.

**Pull request merged**
